apiVersion: v1
kind: Secret
metadata:
  name: nginx-server-credentials
  namespace: nginx-lb-operator-system
type: Opaque
data:
  NGINX_SERVER_IP: base64-encoded-nginx-server-ip
  NGINX_USER: base64-encoded-username
  NGINX_SSH_PRIVATE_KEY: base64-encoded-private-key
  NGINX_KNOWN_HOSTS: base64-encoded-known-hosts