apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-lb-operator-role
rules:
  - apiGroups: [""]
    resources:
      - services
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources:
      - services/status
    verbs: ["update", "patch"]
  - apiGroups: [""]
    resources:
      - endpoints
      - configmaps
      - secrets
      - nodes
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
